      - name: IHS sunucusuna yukle
        timeout-minutes: 3
        run: |
          lftp <<EOF
          set cmd:fail-exit yes
          set net:timeout 20
          set net:max-retries 2
          set net:reconnect-interval-base 5
          set ftp:ssl-allow no
          set ftp:passive-mode yes
          set ftp:use-epsv no

          open -u "${{ secrets.FTP_USERNAME }}","${{ secrets.FTP_PASSWORD }}" ftp://${{ secrets.FTP_SERVER }}

          cd "${{ secrets.FTP_DIRECTORY }}"

          mirror --reverse --verbose \
            --exclude-glob .git/ \
            --exclude-glob .git/** \
            --exclude-glob .github/ \
            --exclude-glob .github/** \
            --exclude-glob node_modules/ \
            --exclude-glob node_modules/** \
            . .

          bye
          EOF
